-- | bmp/*.png from <https://flagpedia.net/download/images>
-- this lists the 2 letter code, the emoji, and allowable country names
module Bmp where

sporcle = [
  ("AF", "🇦🇫", ["Afghanistan"]),
  ("AL", "🇦🇱", ["Albania"]),
  ("DZ", "🇩🇿", ["Algeria"]),
  ("AD", "🇦🇩", ["Andorra"]),
  ("AO", "🇦🇴", ["Angola"]),
  ("AG", "🇦🇬", ["Antigua and Barbuda"]),
  ("AR", "🇦🇷", ["Argentina"]),
  ("AM", "🇦🇲", ["Armenia"]),
  ("AU", "🇦🇺", ["Australia"]),
  ("AT", "🇦🇹", ["Austria"]),
  ("AZ", "🇦🇿", ["Azerbaijan"]),
  ("BS", "🇧🇸", ["Bahamas"]),
  ("BH", "🇧🇭", ["Bahrain"]),
  ("BD", "🇧🇩", ["Bangladesh"]),
  ("BB", "🇧🇧", ["Barbados"]),
  ("BY", "🇧🇾", ["Belarus"]),
  ("BE", "🇧🇪", ["Belgium"]),
  ("BG", "🇧🇬", ["Bulgaria"]),
  ("BF", "🇧🇫", ["Burkina Faso"]),
  ("BI", "🇧🇮", ["Burundi"]),
  ("KH", "🇰🇭", ["Cambodia"]),
  ("CM", "🇨🇲", ["Cameroon"]),
  ("CA", "🇨🇦", ["Canada"]),
  ("CV", "🇨🇻", ["Cape Verde", "Cabo Verde"]),
  ("CF", "🇨🇫", ["Central African Republic", "CAR"]),
  ("TD", "🇹🇩", ["Chad"]),
  ("CL", "🇨🇱", ["Chile"]),
  ("CN", "🇨🇳", ["China"]),
  ("CO", "🇨🇴", ["Colombia"]),
  ("KM", "🇰🇲", ["Comoros"]),
  ("CR", "🇨🇷", ["Costa Rica"]),
  ("HR", "🇭🇷", ["Croatia"]),
  ("CU", "🇨🇺", ["Cuba"]),
  ("CY", "🇨🇾", ["Cyprus"]),
  ("CZ", "🇨🇿", ["Czechia"]),
  ("CD", "🇨🇩", ["Democratic Republic of the Congo", "DRC"]),
  ("DK", "🇩🇰", ["Denmark"]),
  ("DJ", "🇩🇯", ["Djibouti"]),
  ("DM", "🇩🇲", ["Dominica"]),
  ("DO", "🇩🇴", ["Dominican Republic"]),
  ("TL", "🇹🇱", ["East Timor", "Timor-Leste"]),
  ("EC", "🇪🇨", ["Ecuador"]),
  ("EG", "🇪🇬", ["Egypt"]),
  ("SV", "🇸🇻", ["El Salvador"]),
  ("GQ", "🇬🇶", ["Equatorial Guinea"]),
  ("ER", "🇪🇷", ["Eritrea"]),
  ("EE", "🇪🇪", ["Estonia"]),
  ("SZ", "🇸🇿", ["Eswatini", "Swaziland"]),
  ("ET", "🇪🇹", ["Ethiopia"]),
  ("FJ", "🇫🇯", ["Fiji"]),
  ("FI", "🇫🇮", ["Finland"]),
  ("FR", "🇫🇷", ["France"]),
  ("GA", "🇬🇦", ["Gabon"]),
  ("GM", "🇬🇲", ["Gambia"]),
  ("GE", "🇬🇪", ["Georgia"]),
  ("DE", "🇩🇪", ["Germany"]),
  ("GH", "🇬🇭", ["Ghana"]),
  ("GR", "🇬🇷", ["Greece"]),
  ("GD", "🇬🇩", ["Grenada"]),
  ("GT", "🇬🇹", ["Guatemala"]),
  ("GN", "🇬🇳", ["Guinea"]),
  ("GW", "🇬🇼", ["Guinea-Bissau", "Guinea Bissau"]),
  ("GY", "🇬🇾", ["Guyana"]),
  ("HT", "🇭🇹", ["Haiti"]),
  ("HN", "🇭🇳", ["Honduras"]),
  ("HU", "🇭🇺", ["Hungary"]),
  ("IS", "🇮🇸", ["Iceland"]),
  ("IN", "🇮🇳", ["India"]),
  ("ID", "🇮🇩", ["Indonesia"]),
  ("IR", "🇮🇷", ["Iran"]),
  ("IQ", "🇮🇶", ["Iraq"]),
  ("IE", "🇮🇪", ["Ireland"]),
  ("IL", "🇮🇱", ["Israel"]),
  ("IT", "🇮🇹", ["Italy"]),
  ("CI", "🇨🇮", ["Ivory Coast", "Côte d’Ivoire"]),
  ("JM", "🇯🇲", ["Jamaica"]),
  ("JP", "🇯🇵", ["Japan"]),
  ("JO", "🇯🇴", ["Jordan"]),
  ("KZ", "🇰🇿", ["Kazakhstan"]),
  ("KE", "🇰🇪", ["Kenya"]),
  ("KI", "🇰🇮", ["Kiribati"]),
  ("XK", "🇽🇰", ["Kosovo"]),
  ("KW", "🇰🇼", ["Kuwait"]),
  ("KG", "🇰🇬", ["Kyrgyzstan"]),
  ("LA", "🇱🇦", ["Laos"]),
  ("LV", "🇱🇻", ["Latvia"]),
  ("LB", "🇱🇧", ["Lebanon"]),
  ("LS", "🇱🇸", ["Lesotho"]),
  ("LR", "🇱🇷", ["Liberia"]),
  ("LY", "🇱🇾", ["Libya"]),
  ("LI", "🇱🇮", ["Liechtenstein"]),
  ("LT", "🇱🇹", ["Lithuania"]),
  ("LU", "🇱🇺", ["Luxembourg"]),
  ("MG", "🇲🇬", ["Madagascar"]),
  ("MW", "🇲🇼", ["Malawi"]),
  ("MY", "🇲🇾", ["Malaysia"]),
  ("MV", "🇲🇻", ["Maldives"]),
  ("ML", "🇲🇱", ["Mali"]),
  ("MT", "🇲🇹", ["Malta"]),
  ("MH", "🇲🇭", ["Marshall Islands"]),
  ("MR", "🇲🇷", ["Mauritania"]),
  ("MU", "🇲🇺", ["Mauritius"]),
  ("MX", "🇲🇽", ["Mexico"]),
  ("FM", "🇫🇲", ["Micronesia"]),
  ("MD", "🇲🇩", ["Moldova"]),
  ("MC", "🇲🇨", ["Monaco"]),
  ("MN", "🇲🇳", ["Mongolia"]),
  ("ME", "🇲🇪", ["Montenegro"]),
  ("MA", "🇲🇦", ["Morocco"]),
  ("MZ", "🇲🇿", ["Mozambique"]),
  ("MM", "🇲🇲", ["Myanmar","Burma"]),
  ("NA", "🇳🇦", ["Namibia"]),
  ("NR", "🇳🇷", ["Nauru"]),
  ("NP", "🇳🇵", ["Nepal"]),
  ("NL", "🇳🇱", ["Netherlands"]),
  ("NZ", "🇳🇿", ["New Zealand"]),
  ("NI", "🇳🇮", ["Nicaragua"]),
  ("NE", "🇳🇪", ["Niger"]),
  ("NG", "🇳🇬", ["Nigeria"]),
  ("KP", "🇰🇵", ["North Korea"]),
  ("MK", "🇲🇰", ["North Macedonia", "Macedonia"]),
  ("NO", "🇳🇴", ["Norway"]),
  ("OM", "🇴🇲", ["Oman"]),
  ("PK", "🇵🇰", ["Pakistan"]),
  ("PW", "🇵🇼", ["Palau"]),
  ("PS", "🇵🇸", ["Palestine", "Palestinian Territories"]),
  ("PA", "🇵🇦", ["Panama"]),
  ("PG", "🇵🇬", ["Papua New Guinea"]),
  ("PY", "🇵🇾", ["Paraguay"]),
  ("PE", "🇵🇪", ["Peru"]),
  ("PH", "🇵🇭", ["Philippines"]),
  ("PL", "🇵🇱", ["Poland"]),
  ("PT", "🇵🇹", ["Portugal"]),
  ("QA", "🇶🇦", ["Qatar"]),
  ("CG", "🇨🇬", ["Republic of the Congo"]),
  ("RO", "🇷🇴", ["Romania"]),
  ("RU", "🇷🇺", ["Russia"]),
  ("RW", "🇷🇼", ["Rwanda"]),
  ("WS", "🇼🇸", ["Samoa"]),
  ("SM", "🇸🇲", ["San Marino"]),
  ("ST", "🇸🇹", ["São Tomé & Príncipe", "Sao Tome and Principe"]),
  ("SA", "🇸🇦", ["Saudi Arabia"]),
  ("SN", "🇸🇳", ["Senegal"]),
  ("RS", "🇷🇸", ["Serbia"]),
  ("SC", "🇸🇨", ["Seychelles"]),
  ("SL", "🇸🇱", ["Sierra Leone"]),
  ("SG", "🇸🇬", ["Singapore"]),
  ("SK", "🇸🇰", ["Slovakia"]),
  ("SI", "🇸🇮", ["Slovenia"]),
  ("SB", "🇸🇧", ["Solomon Islands"]),
  ("SO", "🇸🇴", ["Somalia"]),
  ("ZA", "🇿🇦", ["South Africa"]),
  ("KR", "🇰🇷", ["South Korea"]),
  ("SS", "🇸🇸", ["South Sudan"]),
  ("ES", "🇪🇸", ["Spain"]),
  ("LK", "🇱🇰", ["Sri Lanka"]),
  ("KN", "🇰🇳", ["St Kitts and Nevis"]),
  ("LC", "🇱🇨", ["St Lucia"]),
  ("VC", "🇻🇨", ["St Vincent and Grenadines", "St Vincent"]),
  ("SD", "🇸🇩", ["Sudan"]),
  ("SR", "🇸🇷", ["Suriname"]),
  ("SE", "🇸🇪", ["Sweden"]),
  ("CH", "🇨🇭", ["Switzerland"]),
  ("SY", "🇸🇾", ["Syria"]),
  ("TW", "🇹🇼", ["Taiwan"]),
  ("TJ", "🇹🇯", ["Tajikistan"]),
  ("TZ", "🇹🇿", ["Tanzania"]),
  ("TH", "🇹🇭", ["Thailand"]),
  ("TG", "🇹🇬", ["Togo"]),
  ("TO", "🇹🇴", ["Tonga"]),
  ("TT", "🇹🇹", ["Trinidad and Tobago"]),
  ("TN", "🇹🇳", ["Tunisia"]),
  ("TR", "🇹🇷", ["Turkey"]),
  ("TM", "🇹🇲", ["Turkmenistan"]),
  ("TV", "🇹🇻", ["Tuvalu"]),
  ("UG", "🇺🇬", ["Uganda"]),
  ("UA", "🇺🇦", ["Ukraine"]),
  ("AE", "🇦🇪", ["United Arab Emirates", "UAE"]),
  ("GB", "🇬🇧", ["United Kingdom", "UK"]),
  ("US", "🇺🇸", ["United States", "USA"]),
  ("UY", "🇺🇾", ["Uruguay"]),
  ("UZ", "🇺🇿", ["Uzbekistan"]),
  ("VU", "🇻🇺", ["Vanuatu"]),
  ("VA", "🇻🇦", ["Vatican City", "Vatican"]),
  ("VE", "🇻🇪", ["Venezuela"]),
  ("VN", "🇻🇳", ["Vietnam"]),
  ("YE", "🇾🇪", ["Yemen"]),
  ("ZM", "🇿🇲", ["Zambia"]),
  ("ZW", "🇿🇼", ["Zimbabwe"]) ]

others = [
  ("AX", "🇦🇽", ["Åland Islands"]),
  ("AS", "🇦🇸", ["American Samoa"]),
  ("AI", "🇦🇮", ["Anguilla"]),
  ("AQ", "🇦🇶", ["Antarctica"]),
  ("AW", "🇦🇼", ["Aruba"]),
  ("AC", "🇦🇨", ["Ascension Island"]),
  ("BM", "🇧🇲", ["Bermuda"]),
  ("BV", "🇧🇻", ["Bouvet Island"]),
  ("IO", "🇮🇴", ["British Indian Ocean Territory"]),
  ("VG", "🇻🇬", ["British Virgin Islands"]),
  ("IC", "🇮🇨", ["Canary Islands"]),
  ("BQ", "🇧🇶", ["Caribbean Netherlands"]),
  ("KY", "🇰🇾", ["Cayman Islands"]),
  ("EA", "🇪🇦", ["Ceuta & Melilla"]),
  ("CX", "🇨🇽", ["Christmas Island"]),
  ("CP", "🇨🇵", ["Clipperton Island"]),
  ("CC", "🇨🇨", ["Cocos (Keeling) Islands"]),
  ("CK", "🇨🇰", ["Cook Islands"]),
  ("CW", "🇨🇼", ["Curaçao"]),
  ("DG", "🇩🇬", ["Diego Garcia"]),
  ("EU", "🇪🇺", ["European Union"]),
  ("FK", "🇫🇰", ["Falkland Islands"]),
  ("FO", "🇫🇴", ["Faroe Islands"]),
  ("GF", "🇬🇫", ["French Guiana"]),
  ("PF", "🇵🇫", ["French Polynesia"]),
  ("TF", "🇹🇫", ["French Southern Territories"]),
  ("GI", "🇬🇮", ["Gibraltar"]),
  ("GL", "🇬🇱", ["Greenland"]),
  ("GP", "🇬🇵", ["Guadeloupe"]),
  ("GU", "🇬🇺", ["Guam"]),
  ("GG", "🇬🇬", ["Guernsey"]),
  ("HM", "🇭🇲", ["Heard & McDonald Islands"]),
  ("HK", "🇭🇰", ["Hong Kong SAR China"]),
  ("IM", "🇮🇲", ["Isle of Man"]),
  ("JE", "🇯🇪", ["Jersey"]),
  ("MO", "🇲🇴", ["Macao SAR China"]),
  ("MQ", "🇲🇶", ["Martinique"]),
  ("YT", "🇾🇹", ["Mayotte"]),
  ("MS", "🇲🇸", ["Montserrat"]),
  ("NC", "🇳🇨", ["New Caledonia"]),
  ("NF", "🇳🇫", ["Norfolk Island"]),
  ("MP", "🇲🇵", ["Northern Mariana Islands"]),
  ("PN", "🇵🇳", ["Pitcairn Islands"]),
  ("PR", "🇵🇷", ["Puerto Rico"]),
  ("RE", "🇷🇪", ["Réunion"]),
  ("SX", "🇸🇽", ["Sint Maarten"]),
  ("GS", "🇬🇸", ["South Georgia & South Sandwich Islands"]),
  ("BL", "🇧🇱", ["St. Barthélemy"]),
  ("SH", "🇸🇭", ["St. Helena"]),
  ("MF", "🇲🇫", ["St. Martin"]),
  ("SJ", "🇸🇯", ["Svalbard & Jan Mayen"]),
  ("TA", "🇹🇦", ["Tristan da Cunha"]),
  ("TC", "🇹🇨", ["Turks & Caicos Islands"]),
  ("UN", "🇺🇳", ["United Nations"]),
  ("UM", "🇺🇲", ["U.S. Outlying Islands"]),
  ("VI", "🇻🇮", ["U.S. Virgin Islands"]),
  ("WF", "🇼🇫", ["Wallis & Futuna"]),
  ("EH", "🇪🇭", ["Western Sahara"]) ]
