name: worldflags
synopsis: Practice typing country names given their flags.
license-file: LICENSE
dependencies:
  - base
  - gloss
  - combinat
  - cmdargs
  - lens
  - zippers
  - binary
  - filepath
  - directory
  - random
  - gloss-juicy
  - monadic-bang
  - time
  - containers
  - split

tested-with: GHC == 9.8.2

data-files: bmp/*.png

executable:
  main:
    main.hs
  source-dirs: .
